### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by BlueSky-fur** [Ceylo/FurAffinityApp#1]
Hello! Installed the latest version and logged in, it's just a blackscreen nothing loads. :/

Using the latest IOS version 16.0.2

**Comment by Ceylo** [comment]
Hey! You just created the first issue, congratulations! (I guess 😅)

Do you get the bottom tabs or not even these? Ideally please share a screenshot.
Is your FA account configured to use the "Classic" or "Modern" template? This is in Settings > Account Settings on FA.

**Comment by BlueSky-fur** [comment]
![image](https://user-images.githubusercontent.com/80676050/193874422-0091b812-1b99-4418-a2c7-b18a48c675f2.png)

There ya go!

Tried both templates

**Comment by BlueSky-fur** [comment]
Cleared my cache and researched to classic, now it looks like I'm browsing the normal site 

![image](https://user-images.githubusercontent.com/80676050/193890658-74bfe8ce-58cc-460e-93de-c9f5d6875467.png)


Would love if the modern one with the modern ui would work

**Comment by BlueSky-fur** [comment]
Will check!

**Comment by BlueSky-fur** [comment]
sorry if im a bit stupid, so i can only see my own submissions on your app?

i freshly created my account yesterday, didnt have one before. 

so theres no submissions there at all

**Comment by Ceylo** [comment]
You can indeed only see when artists post new drawings after you have watched (subscribed) to them. A bit like you’d get content from people you follow on Twitter. That’s what the Submissions tab is.

Currently the app is not designed for general exploration on FA so you only get content from these subscriptions.

It’s still good that you raised the issue because when there’re no submission to show I should probably add a message like « There’re no submissions yet, watch artists and wait for them to post to see the new submissions here! »

**Comment by BlueSky-fur** [comment]
I seeeee. I’ll try, follow some and then check back!

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Lucas ***@***.***>
Gesendet: Wednesday, October 5, 2022 9:34:50 AM
An: Ceylo/FurAffinityApp ***@***.***>
Cc: BlueSky ***@***.***>; State change ***@***.***>
Betreff: Re: [Ceylo/FurAffinityApp] Latest version (Issue #1)


You can indeed only see when artists post new drawings after you have watched (subscribed) to them. A bit like you’d get content from people you follow on Twitter. That’s what the Submissions tab is.

Currently the app is not designed for general exploration on FA so you only get content from these subscriptions.

It’s still good that you raised the issue because when there’re no submission to show I should probably add a message like « There’re no submissions yet, watch artists and wait for them to post to see the new submissions here! »

**Comment by BlueSky-fur** [comment]
> You can indeed only see when artists post new drawings after you have watched (subscribed) to them. A bit like you’d get content from people you follow on Twitter. That’s what the Submissions tab is.
> 
> Currently the app is not designed for general exploration on FA so you only get content from these subscriptions.
> 
> It’s still good that you raised the issue because when there’re no submission to show I should probably add a message like « There’re no submissions yet, watch artists and wait for them to post to see the new submissions here! »

tested now, still cant see anything, when directly on the furaffinity site i do see submissions.

**Comment by Ceylo** [comment]
Okay, I will prepare a build to collect logs in the coming days.

**Comment by Ceylo** [comment]
@BlueSky-fur I just published a new version where you can export logs: https://github.com/Ceylo/FurAffinityApp/releases/tag/1.3.2
Note that the log file may contain personal information such as which submission you try to view or which artists appear in your submissions list so you may want to send the file to revues.terminus-0x@icloud.com (temporary e-mail address that redirects to my mailbox) instead of sharing it here.

**Comment by Ceylo** [comment]
And a small teaser for what's to come in next release when there're no submission or note to list yet:
<img width="293" alt="Simulator Screen Shot - iPhone 13 Pro - 2022-10-15 at 14 30 17" src="https://user-images.githubusercontent.com/451334/196047597-b34badea-f98f-4ba3-95ca-51071db8a227.png"> <img width="293" alt="Simulator Screen Shot - iPhone 13 Pro - 2022-10-15 at 14 47 16" src="https://user-images.githubusercontent.com/451334/196047600-ef16f50f-1d4f-4e58-a991-cde8f60e0b73.png">

**Comment by BlueSky-fur** [comment]
> want

i will get to it right after vacation! 1 week from now on

**Comment by Ceylo** [comment]
Hi @BlueSky-fur, I'm coming for news about this problem 🙂
You can provide logs with version 1.3.2 or 1.4.0 that I just released, both will give the same amount of information.

**Comment by Ceylo** [comment]
Closed since there was no feedback. Feel free to reopen if you have more input.
