### ISSUE TITLE
Watch list

### ISSUE THREAD

**Issue by HideOnFluff** [Ceylo/FurAffinityApp#2]
Hey! this app is amazing! I love it so far

I'd like to request the ability to see my watchlist or to filter the submission feed by artist if possible (if is not the priority right now then I can wait for the Exploration milestone x) keep it up!)

**Comment by Ceylo** [comment]
Hey I'm glad you like it!
When you say filtering the submission feed by artist, it would be equivalent to viewing the gallery of an artist, am I right?
The thing is that right now, the submission feed is equivalent to checking your first page of submissions, that is up to 72 items. Fetching more than the first page hasn't been implemented yet, so if you scroll to the bottom you could end up missing older results. Fortunately as long as the app keeps running, new submissions are accumulated at the beginning so it might look like old submissions listing "works" :p

This means that if a filter on artist were to be added now, it would only show results among these 72 results (or a bit more depending on how long the app has been running), which might not be what you had in mind. I expect a better solution will indeed being able to go to your watch list then the artist gallery. I'm not sure yet how this would be presented in the app but it's definitely doable.

**Comment by Ceylo** [comment]
Hello!
It's been almost two years but… in case you're still using the app, I wanted to let you know that watchlists are coming in the next release 🙂
Obviously this also works when going to your own user page through the profile tab, which allows you to see the gallery from any artist you're watching.
Let me know if you have any other wish on this feature!

Here are a few screenshots from the development version:
<img alt="Simulator Screenshot - iPhone 15 Pro - 2024-09-03 at 16 52 12" src="https://github.com/user-attachments/assets/90ba8467-ed7b-4a1f-82e3-cbfb3ba9b299" width="393" />
<img alt="Simulator Screenshot - iPhone 15 Pro - 2024-09-03 at 16 53 00" src="https://github.com/user-attachments/assets/126a1ad6-2514-4565-9bf4-443453de48a2" width="393" />

**Comment by HideOnFluff** [comment]
omgg! that's so cool :33

I haven't used the app since 2022 due to airserver not working on my mac anymore after the Ventura update xwx but I will give it a go again as soon as I can :3 that solves it perfectly!!! and thank you so much for notifying me<3

**Comment by HideOnFluff** [comment]
woops, closed by mistake xwx

**Comment by Ceylo** [comment]
Hmmm… why is airserver needed?
Also note that since then, it’s been made easier to stay updated through AltStore thanks to a new source. You can find more about it on the also new website : https://furaffinity.app

In any case, good luck 😉

**Comment by Ceylo** [comment]
Hey @HideOnFluff,
[Version 1.9](https://github.com/Ceylo/FurAffinityApp/releases/tag/1.9.0) with watchlist is live!
