### ISSUE TITLE
App crashes with trollstore

### ISSUE THREAD

**Issue by Lrive** [Ceylo/FurAffinityApp#4]
When opening with trollstore, app instantly crashes, iPhone 8 iOS 15.1

**Comment by Lrive** [comment]
just read the description, sorry

**Comment by Ceylo** [comment]
Hello,
You can use [version 1.4.1 of the app](https://github.com/Ceylo/FurAffinityApp/releases/tag/1.4.1) if you want to stay on iOS 15, or upgrade to iOS 16, up to you.

**Comment by Lrive** [comment]
yeah I already am using 1.4.1 thanks!
