### ISSUE TITLE
iOS issue

### ISSUE THREAD

**Issue by braden697** [Ceylo/FurAffinityApp#5]
Hi, I recently downloaded the fur affinity app, today. But I do not know how to open the extracted files. Is it possible if you just send it or upload the app to the App Store?

**Comment by Ceylo** [comment]
Hi,
Unfortunately I cannot "just send it or upload the app to the App Store". I wish I could ! I already tried and Apple refused the app.

Did you read and follow the steps from https://github.com/Ceylo/FurAffinityApp#installation ? There’s no simpler way for now.
