### ISSUE TITLE
AltStore source not working with SideStore

### ISSUE THREAD

**Issue by LeviSnoot** [Ceylo/FurAffinityApp#6]
Unable to check if this issue also affects AltStore as I don't have a device with it installed. SideStore is a fork of AltStore and all the sources I've tried with it in the past work fine, so I'm thinking this may also affect vanilla AltStore.

When I try to add the source in SideStore, I get the following error message:

```
The data couldn't be read because it is missing.

No value associated with key CodingKeys(stringValue: "identifier", intValue: nil) ("identifier").
```

Checking another working source I have on SideStore it does indeed contain the key `"identifier"`, but the source for the FurAffinity iOS app appears not to.

**Comment by Ceylo** [comment]
Hello!
I built the source from [AltStore's source documentation](https://faq.altstore.io/distribute-your-apps/make-a-source) which doesn't mention this `identifier`, and AltStore is happy without it. In fact it looks like SideStore is [currently using an outdated schema when loading sources](https://github.com/SideStore/SideStore/issues/314), hence the issue your ran into.

Nevertheless, I updated the source in 04b676c4966e6b53cddc2cfcad70b0f93c1b4151 and it looks now compatible both with AltStore and SideStore. SideStore screenshot handling is a bit limited so it'll look a bit stretched but that's only a minor inconvenience!

Could you try adding the source again?

<img alt="IMG_8117" src="https://github.com/user-attachments/assets/68818def-979b-4677-beae-f52ad7f3f3e2" width="390px" />

**Comment by LeviSnoot** [comment]
That did the trick, I appreciate you looking into it and fixing it so quickly! 💖
